import { InMemoryDbService } from "angular-in-memory-web-api";

export class InMemoryRepository extends InMemoryDbService {

  createDb() {
    console.log('Inizializzato db');
    let utenti = [
      { id: 1, email: "admin@unibas.it", password: "admin" },
      { id: 2, email: "prova@prova.it", password: "prova" },
    ];
    let esami = [
      { id: 10, studenteId: 1, insegnamento: 'POO2', voto: 30, lode: true,
      crediti: 4, dataRegistrazione: new Date() }
    ]
    let studenti = [
      {
        id: 1, nome: 'Jack', cognome: 'Sparrow', matricola: '12345', annoIscrizione: 2023, esami: []
        // esami: [esami[0]]
      },
      { id: 2, nome: 'John', cognome: 'Doe', matricola: '1984', annoIscrizione: 2023, esami: [] },
      { id: 3, nome: 'Mario', cognome: 'Rossi', matricola: '5548', annoIscrizione: 2023, esami: [] },
      { id: 4, nome: "Sharlene", cognome: "Pristnor", annoIscrizione: 2020, matricola: 8015, esami: [] },
      { id: 5, nome: "Hamish", cognome: "Edwins", annoIscrizione: 2021, matricola: 6789, esami: [] },
      { id: 6, nome: "Leonora", cognome: "Mayers", annoIscrizione: 2020, matricola: 5867, esami: [] },
      { id: 7, nome: "Marcelo", cognome: "Suttling", annoIscrizione: 2022, matricola: 5801, esami: [] },
      { id: 8, nome: "Clayborn", cognome: "Maylard", annoIscrizione: 2020, matricola: 7574, esami: [] },
      { id: 9, nome: "Herman", cognome: "Molyneux", annoIscrizione: 2021, matricola: 6603, esami: [] },
      { id: 10, nome: "Marcello", cognome: "Fearneley", annoIscrizione: 2023, matricola: 7575, esami: [] },
      { id: 11, nome: "Lola", cognome: "Athridge", annoIscrizione: 2020, matricola: 8893, esami: [] },
      { id: 12, nome: "Rochette", cognome: "Gallaccio", annoIscrizione: 2022, matricola: 5176, esami: [] },
      { id: 13, nome: "Corilla", cognome: "Keepence", annoIscrizione: 2022, matricola: 8278, esami: [] },
      { id: 14, nome: "Had", cognome: "Youel", annoIscrizione: 2022, matricola: 6443, esami: [] },
      { id: 15, nome: "Lorie", cognome: "Meyrick", annoIscrizione: 2020, matricola: 8881, esami: [] },
      { id: 16, nome: "Emmi", cognome: "Bariball", annoIscrizione: 2023, matricola: 5107, esami: [] },
      { id: 17, nome: "Farlay", cognome: "Doddridge", annoIscrizione: 2020, matricola: 8963, esami: [] },
      { id: 18, nome: "Libbi", cognome: "Bough", annoIscrizione: 2023, matricola: 8063, esami: [] },
      { id: 19, nome: "Stephani", cognome: "Larner", annoIscrizione: 2022, matricola: 8626, esami: [] },
      { id: 20, nome: "Byrle", cognome: "Larham", annoIscrizione: 2020, matricola: 5194, esami: [] },
      { id: 21, nome: "Jarrod", cognome: "Mattson", annoIscrizione: 2021, matricola: 5716, esami: [] },
      { id: 22, nome: "Felix", cognome: "Slessor", annoIscrizione: 2021, matricola: 6131, esami: [] },
      { id: 23, nome: "Tonia", cognome: "Hawk", annoIscrizione: 2022, matricola: 8656, esami: [] },
      { id: 24, nome: "Zaneta", cognome: "Draye", annoIscrizione: 2022, matricola: 6893, esami: [] },
      { id: 25, nome: "Erinna", cognome: "McLean", annoIscrizione: 2022, matricola: 5899, esami: [] },
      { id: 26, nome: "Justin", cognome: "Luipold", annoIscrizione: 2023, matricola: 7753, esami: [] },
      { id: 27, nome: "Hilliard", cognome: "Molan", annoIscrizione: 2020, matricola: 5366, esami: [] },
      { id: 28, nome: "Ilysa", cognome: "Yearne", annoIscrizione: 2021, matricola: 6139, esami: [] },
      { id: 29, nome: "Mattheus", cognome: "Beckles", annoIscrizione: 2021, matricola: 7139, esami: [] },
      { id: 30, nome: "Claudio", cognome: "Bryenton", annoIscrizione: 2023, matricola: 6021, esami: [] },
      { id: 31, nome: "Walker", cognome: "Jansens", annoIscrizione: 2020, matricola: 6332, esami: [] },
      { id: 32, nome: "Alyce", cognome: "Sellars", annoIscrizione: 2021, matricola: 5221, esami: [] },
      { id: 33, nome: "Joni", cognome: "Braffington", annoIscrizione: 2021, matricola: 7256, esami: [] },
      { id: 34, nome: "Walliw", cognome: "Kenewell", annoIscrizione: 2023, matricola: 8052, esami: [] },
      { id: 35, nome: "Andra", cognome: "Burgoyne", annoIscrizione: 2020, matricola: 7981, esami: [] },
      { id: 36, nome: "Wait", cognome: "Bariball", annoIscrizione: 2020, matricola: 7017, esami: [] },
      { id: 37, nome: "Rivalee", cognome: "Beldham", annoIscrizione: 2021, matricola: 6941, esami: [] },
      { id: 38, nome: "Bellina", cognome: "Folland", annoIscrizione: 2022, matricola: 8339, esami: [] },
      { id: 39, nome: "Caritta", cognome: "Jardin", annoIscrizione: 2021, matricola: 5145, esami: [] },
      { id: 40, nome: "Vito", cognome: "Foxen", annoIscrizione: 2023, matricola: 5202, esami: [] },
      { id: 41, nome: "Chic", cognome: "Hullett", annoIscrizione: 2021, matricola: 8123, esami: [] },
      { id: 42, nome: "De witt", cognome: "Joiris", annoIscrizione: 2021, matricola: 8798, esami: [] },
      { id: 43, nome: "Sunny", cognome: "Drew", annoIscrizione: 2020, matricola: 5013, esami: [] },
      { id: 44, nome: "Damian", cognome: "Caughtry", annoIscrizione: 2023, matricola: 5108, esami: [] },
      { id: 45, nome: "Munroe", cognome: "Tolle", annoIscrizione: 2021, matricola: 7874, esami: [] },
      { id: 46, nome: "Elinor", cognome: "Gadsdon", annoIscrizione: 2023, matricola: 7130, esami: [] },
      { id: 47, nome: "Armstrong", cognome: "Tressler", annoIscrizione: 2021, matricola: 5881, esami: [] },
      { id: 48, nome: "Krista", cognome: "Bare", annoIscrizione: 2022, matricola: 8392, esami: [] },
      { id: 49, nome: "Adrian", cognome: "Goodisson", annoIscrizione: 2022, matricola: 6135, esami: [] },
      { id: 50, nome: "Tressa", cognome: "Hughes", annoIscrizione: 2023, matricola: 5237, esami: [] },
      { id: 51, nome: "Kalina", cognome: "Sicely", annoIscrizione: 2023, matricola: 6094, esami: [] },
      { id: 52, nome: "Jobyna", cognome: "Moodycliffe", annoIscrizione: 2023, matricola: 8466, esami: [] },
      { id: 53, nome: "Artair", cognome: "Lampkin", annoIscrizione: 2023, matricola: 7576, esami: [] },
      { id: 54, nome: "Jeane", cognome: "Akrigg", annoIscrizione: 2020, matricola: 8822, esami: [] },
      { id: 55, nome: "Cassandry", cognome: "McGebenay", annoIscrizione: 2021, matricola: 8813, esami: [] },
      { id: 56, nome: "Betta", cognome: "Matysiak", annoIscrizione: 2020, matricola: 8601, esami: [] },
      { id: 57, nome: "Erv", cognome: "Winckle", annoIscrizione: 2020, matricola: 8663, esami: [] },
      { id: 58, nome: "Leonanie", cognome: "Howley", annoIscrizione: 2023, matricola: 5666, esami: [] },
      { id: 59, nome: "Corbie", cognome: "Critchard", annoIscrizione: 2020, matricola: 8650, esami: [] },
      { id: 60, nome: "Jeremy", cognome: "Jindrich", annoIscrizione: 2022, matricola: 6570, esami: [] },
      { id: 61, nome: "Stormie", cognome: "Pawlick", annoIscrizione: 2022, matricola: 6170, esami: [] },
      { id: 62, nome: "Cymbre", cognome: "Cradduck", annoIscrizione: 2022, matricola: 6704, esami: [] },
      { id: 63, nome: "Ede", cognome: "Clutterbuck", annoIscrizione: 2020, matricola: 6612, esami: [] },
      { id: 64, nome: "Newton", cognome: "Jessett", annoIscrizione: 2023, matricola: 7766, esami: [] },
      { id: 65, nome: "Wallache", cognome: "Maycey", annoIscrizione: 2023, matricola: 5551, esami: [] },
      { id: 66, nome: "Andrei", cognome: "Prendeville", annoIscrizione: 2020, matricola: 8516, esami: [] },
      { id: 67, nome: "Petronille", cognome: "Greenwood", annoIscrizione: 2022, matricola: 7533, esami: [] },
      { id: 68, nome: "Brien", cognome: "Lempenny", annoIscrizione: 2023, matricola: 6626, esami: [] },
      { id: 69, nome: "Del", cognome: "Zucker", annoIscrizione: 2023, matricola: 8822, esami: [] },
      { id: 70, nome: "Carmina", cognome: "Cary", annoIscrizione: 2022, matricola: 5372, esami: [] },
      { id: 71, nome: "Harlan", cognome: "Surpliss", annoIscrizione: 2021, matricola: 6889, esami: [] },
      { id: 72, nome: "Cos", cognome: "Stiggers", annoIscrizione: 2023, matricola: 6523, esami: [] },
      { id: 73, nome: "Martino", cognome: "Britland", annoIscrizione: 2021, matricola: 8060, esami: [] },
      { id: 74, nome: "Nehemiah", cognome: "Radsdale", annoIscrizione: 2023, matricola: 6938, esami: [] },
      { id: 75, nome: "Cybill", cognome: "Menier", annoIscrizione: 2021, matricola: 7161, esami: [] },
      { id: 76, nome: "Kanya", cognome: "Maving", annoIscrizione: 2023, matricola: 5191, esami: [] },
      { id: 77, nome: "Becka", cognome: "Deftie", annoIscrizione: 2022, matricola: 8039, esami: [] },
      { id: 78, nome: "Galina", cognome: "Kabos", annoIscrizione: 2021, matricola: 6927, esami: [] },
      { id: 79, nome: "Winnie", cognome: "Boyn", annoIscrizione: 2023, matricola: 8941, esami: [] },
      { id: 80, nome: "Alastair", cognome: "Claris", annoIscrizione: 2020, matricola: 6157, esami: [] },
      { id: 81, nome: "Archambault", cognome: "Buff", annoIscrizione: 2020, matricola: 5915, esami: [] },
      { id: 82, nome: "Fawne", cognome: "Strowthers", annoIscrizione: 2021, matricola: 6365, esami: [] },
      { id: 83, nome: "Nora", cognome: "Tzarkov", annoIscrizione: 2023, matricola: 5886, esami: [] },
      { id: 84, nome: "Clemente", cognome: "Sarfas", annoIscrizione: 2022, matricola: 6979, esami: [] },
      { id: 85, nome: "Brok", cognome: "Talmadge", annoIscrizione: 2022, matricola: 7893, esami: [] },
      { id: 86, nome: "Gusella", cognome: "Sturgis", annoIscrizione: 2021, matricola: 6993, esami: [] },
      { id: 87, nome: "Lennie", cognome: "Beesey", annoIscrizione: 2020, matricola: 8632, esami: [] },
      { id: 88, nome: "Carey", cognome: "Heffron", annoIscrizione: 2023, matricola: 5966, esami: [] },
      { id: 89, nome: "Fidole", cognome: "Farnie", annoIscrizione: 2023, matricola: 6158, esami: [] },
      { id: 90, nome: "Drusilla", cognome: "Uman", annoIscrizione: 2022, matricola: 6397, esami: [] },
      { id: 91, nome: "Bruce", cognome: "Brachell", annoIscrizione: 2023, matricola: 8868, esami: [] },
      { id: 92, nome: "Annadiana", cognome: "Brome", annoIscrizione: 2023, matricola: 5994, esami: [] },
      { id: 93, nome: "Petronille", cognome: "Piggot", annoIscrizione: 2020, matricola: 7453, esami: [] },
      { id: 94, nome: "Mart", cognome: "Cade", annoIscrizione: 2021, matricola: 6484, esami: [] },
      { id: 95, nome: "Rosemaria", cognome: "Medley", annoIscrizione: 2022, matricola: 7539, esami: [] },
      { id: 96, nome: "Linda", cognome: "Staining", annoIscrizione: 2023, matricola: 8924, esami: [] },
      { id: 97, nome: "Gothart", cognome: "Finnan", annoIscrizione: 2023, matricola: 6675, esami: [] },
      { id: 98, nome: "Zachery", cognome: "Eyree", annoIscrizione: 2022, matricola: 8590, esami: [] },
      { id: 99, nome: "Rhianna", cognome: "Albiston", annoIscrizione: 2023, matricola: 7889, esami: [] },
      { id: 100, nome: "Nestor", cognome: "Arkcoll", annoIscrizione: 2020, matricola: 7650, esami: [] }
    ];
    return { utenti, studenti, esami };
  }

}
